[package]
name        = "pkix-revocation-http"
description = "Online CRL and OCSP fetching for pkix-revocation"
version               = "0.1.1"
edition.workspace     = true
rust-version.workspace = true
license.workspace     = true
repository.workspace  = true
authors.workspace     = true
keywords    = ["x509", "certificate", "crl", "ocsp", "revocation"]
categories  = ["cryptography"]

[features]
default = []
crl  = ["pkix-revocation/crl"]
ocsp = ["pkix-revocation/ocsp"]

[dependencies]
pkix-path       = { workspace = true }
pkix-revocation = { workspace = true }
der             = { workspace = true }
x509-cert       = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
