//! Integration tests for `pkix_revocation::CrlChecker`.
//!
//! All DER fixtures in tests/fixtures/ were generated by gen_crl_fixtures.py
//! (and gen_delta_crl_fixtures.py for delta CRL fixtures)
//! using pyca/cryptography as the external oracle. Tests run fully offline.
//!
//! Fixture structure:
//!   crl-ca.der             — RSA-2048 self-signed CA (serial=100), CN=Test CRL CA
//!   crl-leaf-good.der      — leaf cert, serial=1 (not revoked)
//!   crl-leaf-revoked.der   — leaf cert, serial=2 (appears in revocation CRLs)
//!   crl-empty.der          — empty CRL, valid 2026-01-01..2027-01-01
//!   crl-with-revocation.der — CRL with serial=2 revoked, no reason code
//!   crl-with-reason.der    — CRL with serial=2 revoked, CRLReason=keyCompromise(1)
//!   crl-expired.der        — CRL whose nextUpdate=2021-01-01 (expired)
//!   crl-bad-sig.der        — crl-empty.der with last signature byte corrupted
//!   delta-crl-ca.der       — RSA-2048 self-signed CA (serial=200), CN=Test Delta CRL CA
//!   delta-crl-leaf-2.der   — leaf cert, serial=2 (revoked in base CRL)
//!   delta-crl-leaf-3.der   — leaf cert, serial=3 (revoked only in delta-add CRL)
//!   delta-crl-leaf-4.der   — leaf cert, serial=4 (revoked in delta-mixed CRL)
//!   delta-crl-base.der     — base CRL: serial=2 revoked, CRLNumber=1
//!   delta-crl-delta-add.der — delta CRL: serial=3 revoked, BaseCRLNumber=1
//!   delta-crl-remove.der   — delta CRL: serial=2 removeFromCRL, BaseCRLNumber=1
//!   delta-crl-mixed.der    — delta CRL: serial=4 revoked + serial=2 removeFromCRL
//!
//! Validation time: 2026-06-01 00:00:00 UTC = 1_780_272_000.
//! All valid CRLs have thisUpdate=2026-01-01, nextUpdate=2027-01-01.

use der::Decode as _;
use pkix_path::{DefaultVerifier, TrustAnchor};
use pkix_revocation::{CrlChecker, Error, RevocationChecker as _};
use x509_cert::{ext::pkix::crl::CrlReason, Certificate};

/// Unix timestamp used as "now" for all tests (2026-06-01 00:00:00 UTC).
const NOW: u64 = 1_780_272_000;

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("read {name}: {e}"))
}

fn load_cert(name: &str) -> Certificate {
    let der = fixture(name);
    Certificate::from_der(&der).unwrap_or_else(|e| panic!("parse {name}: {e}"))
}

fn checker(crl_name: &str) -> CrlChecker<DefaultVerifier> {
    CrlChecker::new(fixture(crl_name), NOW, DefaultVerifier)
}

// ---------------------------------------------------------------------------
// Happy path — no revocation
// ---------------------------------------------------------------------------

/// Good cert (serial=1) against an empty CRL → Ok(()).
///
/// Oracle: pyca/cryptography; crl-empty.der has no revoked entries.
#[test]
fn crl_good_cert_empty_crl_ok() {
    let ca = load_cert("crl-ca.der");
    let good = load_cert("crl-leaf-good.der");
    let result = checker("crl-empty.der").check_revocation(&good, &ca);
    result.expect("good cert against empty CRL must return Ok(())");
}

/// Good cert (serial=1) against a CRL that revokes serial=2 → Ok(()).
///
/// Oracle: serial 1 does not appear in crl-with-revocation.der.
#[test]
fn crl_good_cert_not_in_revoked_list_ok() {
    let ca = load_cert("crl-ca.der");
    let good = load_cert("crl-leaf-good.der");
    let result = checker("crl-with-revocation.der").check_revocation(&good, &ca);
    result.expect("serial=1 cert against CRL revoking serial=2 must return Ok(())");
}

// ---------------------------------------------------------------------------
// Revoked
// ---------------------------------------------------------------------------

/// Revoked cert (serial=2) against crl-with-revocation.der → Err(Revoked) with no reason.
///
/// Oracle: pyca/cryptography; revoked entry has no CRLReason extension.
#[test]
fn crl_cert_revoked_no_reason() {
    let ca = load_cert("crl-ca.der");
    let revoked = load_cert("crl-leaf-revoked.der");
    let result = checker("crl-with-revocation.der").check_revocation(&revoked, &ca);
    assert!(
        matches!(
            result,
            Err(Error::Revoked {
                reason_code: None,
                ..
            })
        ),
        "revoked cert (no reason) must return Revoked {{ reason_code: None }}, got: {result:?}"
    );
}

/// Revoked cert (serial=2) against crl-with-reason.der → Err(Revoked) with reason=KeyCompromise.
///
/// Oracle: pyca/cryptography; CRLReason=keyCompromise (RFC 5280 §5.3.1 value 1).
#[test]
fn crl_cert_revoked_with_reason_key_compromise() {
    let ca = load_cert("crl-ca.der");
    let revoked = load_cert("crl-leaf-revoked.der");
    let result = checker("crl-with-reason.der").check_revocation(&revoked, &ca);
    assert!(
        matches!(result, Err(Error::Revoked { reason_code: Some(CrlReason::KeyCompromise), .. })),
        "revoked cert (keyCompromise) must return Revoked {{ reason_code: Some(KeyCompromise) }}, got: {result:?}"
    );
}

// ---------------------------------------------------------------------------
// CRL validity window
// ---------------------------------------------------------------------------

/// Valid cert against an expired CRL (nextUpdate=2021-01-01 < NOW=2026-06-01) → Err(CrlExpired).
///
/// Oracle: crl-expired.der has nextUpdate=2021-01-01 08:00:00 UTC.
#[test]
fn crl_expired_returns_error() {
    let ca = load_cert("crl-ca.der");
    let good = load_cert("crl-leaf-good.der");
    let result = checker("crl-expired.der").check_revocation(&good, &ca);
    assert!(
        matches!(result, Err(Error::CrlExpired)),
        "expired CRL must return CrlExpired, got: {result:?}"
    );
}

// ---------------------------------------------------------------------------
// Signature errors
// ---------------------------------------------------------------------------

/// Valid cert against a CRL with a corrupted signature → Err(CrlSignatureInvalid).
///
/// Oracle: crl-bad-sig.der is crl-empty.der with last signature byte XOR'd 0xFF.
#[test]
fn crl_bad_signature_returns_error() {
    let ca = load_cert("crl-ca.der");
    let good = load_cert("crl-leaf-good.der");
    let result = checker("crl-bad-sig.der").check_revocation(&good, &ca);
    assert!(
        matches!(result, Err(Error::CrlSignatureInvalid)),
        "corrupted CRL signature must return CrlSignatureInvalid, got: {result:?}"
    );
}

// ---------------------------------------------------------------------------
// Parse errors
// ---------------------------------------------------------------------------

/// Truncated CRL DER → Err(CrlParseError(_)).
#[test]
fn crl_parse_error_truncated_der() {
    let ca = load_cert("crl-ca.der");
    let good = load_cert("crl-leaf-good.der");
    let truncated = vec![0x30, 0x82, 0x01, 0x00, 0xAA, 0xBB]; // garbage
    let checker = CrlChecker::new(truncated, NOW, DefaultVerifier);
    let result = checker.check_revocation(&good, &ca);
    assert!(
        matches!(result, Err(Error::CrlParseError(_))),
        "truncated CRL must return CrlParseError, got: {result:?}"
    );
}

// ---------------------------------------------------------------------------
// check_revocation_against_anchor (PKIX-x1i / CRL path)
// ---------------------------------------------------------------------------

/// check_revocation_against_anchor: cert issued by anchor not in CRL → Ok(()).
///
/// crl-ca.der is treated as the trust anchor (its self-signed cert matches the
/// CRL issuer).  crl-leaf-good.der is the cert immediately issued by that anchor.
/// crl-empty.der is a valid CRL signed by the anchor CA containing no revocations.
///
/// Oracle: pyca/cryptography (gen_crl_fixtures.py); crl-empty.der has no entries.
#[test]
fn crl_check_revocation_against_anchor_good_cert_empty_crl() {
    let anchor_cert = load_cert("crl-ca.der");
    let anchor = TrustAnchor::from(&anchor_cert);
    let leaf = load_cert("crl-leaf-good.der");
    let checker = CrlChecker::new(fixture("crl-empty.der"), NOW, DefaultVerifier);
    let result = checker.check_revocation_against_anchor(&leaf, &anchor);
    result.expect("cert not in CRL issued by anchor must return Ok(())");
}

/// check_revocation_against_anchor: cert in CRL issued by anchor → Err(Revoked).
///
/// crl-with-revocation.der revokes serial=2.  crl-leaf-revoked.der has serial=2.
///
/// Oracle: pyca/cryptography (gen_crl_fixtures.py).
#[test]
fn crl_check_revocation_against_anchor_revoked_cert() {
    let anchor_cert = load_cert("crl-ca.der");
    let anchor = TrustAnchor::from(&anchor_cert);
    let revoked = load_cert("crl-leaf-revoked.der");
    let checker = CrlChecker::new(fixture("crl-with-revocation.der"), NOW, DefaultVerifier);
    let result = checker.check_revocation_against_anchor(&revoked, &anchor);
    assert!(
        matches!(result, Err(Error::Revoked { reason_code: None, .. })),
        "revoked cert must return Revoked when checked via anchor, got: {result:?}"
    );
}

/// check_revocation_against_anchor: CRL issuer does not match anchor subject → Err(CrlIssuerMismatch).
///
/// Supply the leaf cert as the anchor (wrong subject / wrong key) so the CRL
/// issuer name will not match the anchor's subject DN.
///
/// Oracle: crl-empty.der's issuer is CN=CRL Test CA; crl-leaf-good.der's
/// subject is something else (a leaf CN).
#[test]
fn crl_check_revocation_against_anchor_issuer_mismatch() {
    // Load the CRL CA cert and leaf; use the *leaf* cert as the anchor to
    // produce a subject mismatch with the CRL issuer.
    let leaf_cert = load_cert("crl-leaf-good.der");
    let wrong_anchor = TrustAnchor::from(&leaf_cert);
    let checked_cert = load_cert("crl-leaf-good.der");
    let checker = CrlChecker::new(fixture("crl-empty.der"), NOW, DefaultVerifier);
    let result = checker.check_revocation_against_anchor(&checked_cert, &wrong_anchor);
    assert!(
        matches!(result, Err(Error::CrlIssuerMismatch)),
        "CRL issuer ≠ anchor subject must return CrlIssuerMismatch, got: {result:?}"
    );
}

/// check_revocation_against_anchor: expired CRL → Err(CrlExpired).
///
/// crl-expired.der has nextUpdate=2021-01-01 < NOW=2026-06-01.
///
/// Oracle: pyca/cryptography (gen_crl_fixtures.py).
#[test]
fn crl_check_revocation_against_anchor_expired_crl() {
    let anchor_cert = load_cert("crl-ca.der");
    let anchor = TrustAnchor::from(&anchor_cert);
    let good = load_cert("crl-leaf-good.der");
    let checker = CrlChecker::new(fixture("crl-expired.der"), NOW, DefaultVerifier);
    let result = checker.check_revocation_against_anchor(&good, &anchor);
    assert!(
        matches!(result, Err(Error::CrlExpired)),
        "expired CRL in anchor check must return CrlExpired, got: {result:?}"
    );
}

// ---------------------------------------------------------------------------
// Delta CRL tests
//
// All fixtures use a separate CA (CN=Test Delta CRL CA, serial=200) generated
// by gen_delta_crl_fixtures.py (pyca/cryptography). The base CRL has
// CRLNumber=1; all delta CRLs have BaseCRLNumber=1.
//
// Fixture serials:
//   serial=2 — revoked in base CRL
//   serial=3 — revoked only in delta-add CRL (not in base)
//   serial=4 — revoked only in delta-mixed CRL
// ---------------------------------------------------------------------------

/// CrlChecker::with_delta construction succeeds for a valid base+delta pair.
///
/// Oracle: gen_delta_crl_fixtures.py — delta-crl-base.der (CRLNumber=1) and
/// delta-crl-delta-add.der (BaseCRLNumber=1) are a matching pair.
#[test]
fn delta_crl_with_delta_construction_ok() {
    let result = CrlChecker::with_delta(
        fixture("delta-crl-base.der"),
        fixture("delta-crl-delta-add.der"),
        NOW,
        DefaultVerifier,
    );
    assert!(result.is_ok(), "valid base+delta must construct Ok, got: {result:?}");
}

/// CrlChecker::with_delta rejects when the second argument is not a delta CRL.
///
/// Oracle: passing two base CRLs must return DeltaCrlBaseMismatch.
#[test]
fn delta_crl_with_delta_rejects_non_delta() {
    let result = CrlChecker::with_delta(
        fixture("delta-crl-base.der"),
        fixture("delta-crl-base.der"), // base as delta → no deltaCRLIndicator
        NOW,
        DefaultVerifier,
    );
    assert!(
        matches!(result, Err(Error::DeltaCrlBaseMismatch)),
        "non-delta second arg must return DeltaCrlBaseMismatch, got: {result:?}"
    );
}

/// Serial=2 is revoked in the base CRL; even with a delta (serial=3 only),
/// the base entry is visible and the cert is still revoked.
///
/// Oracle: RFC 5280 §5.2.4: base CRL entries that are not in the delta remain revoked.
#[test]
fn delta_crl_base_entry_still_revoked_with_delta() {
    let ca = load_cert("delta-crl-ca.der");
    let leaf2 = load_cert("delta-crl-leaf-2.der");
    let checker = CrlChecker::with_delta(
        fixture("delta-crl-base.der"),
        fixture("delta-crl-delta-add.der"),
        NOW,
        DefaultVerifier,
    )
    .expect("construction must succeed");
    let result = checker.check_revocation(&leaf2, &ca);
    assert!(
        matches!(result, Err(Error::Revoked { .. })),
        "serial=2 revoked in base must remain Revoked even with delta-add; got: {result:?}"
    );
}

/// Serial=3 is revoked only in the delta CRL (not in the base).
/// Without the delta, serial=3 appears as not-revoked.
/// With the delta, serial=3 must be detected as revoked.
///
/// Oracle: RFC 5280 §5.2.4: delta entries add to the merged revocation set.
#[test]
fn delta_crl_delta_entry_detected() {
    let ca = load_cert("delta-crl-ca.der");
    let leaf3 = load_cert("delta-crl-leaf-3.der");

    // Without delta: serial=3 not in base → Ok(()).
    let base_only = CrlChecker::new(fixture("delta-crl-base.der"), NOW, DefaultVerifier);
    let result = base_only.check_revocation(&leaf3, &ca);
    assert!(result.is_ok(), "serial=3 not in base should be Ok; got: {result:?}");

    // With delta: serial=3 in delta → Revoked.
    let with_delta = CrlChecker::with_delta(
        fixture("delta-crl-base.der"),
        fixture("delta-crl-delta-add.der"),
        NOW,
        DefaultVerifier,
    )
    .expect("construction must succeed");
    let result = with_delta.check_revocation(&leaf3, &ca);
    assert!(
        matches!(result, Err(Error::Revoked { .. })),
        "serial=3 revoked in delta must be detected; got: {result:?}"
    );
}

/// Serial=2 is in the base CRL with no reason; the delta CRL contains
/// serial=2 with reason=removeFromCRL, which un-revokes it.
///
/// Oracle: RFC 5280 §5.2.4: a delta entry with removeFromCRL removes the
/// entry from the effective revocation set.
#[test]
fn delta_crl_remove_from_crl_unrevokes() {
    let ca = load_cert("delta-crl-ca.der");
    let leaf2 = load_cert("delta-crl-leaf-2.der");

    // Base only: serial=2 revoked.
    let base_only = CrlChecker::new(fixture("delta-crl-base.der"), NOW, DefaultVerifier);
    let base_result = base_only.check_revocation(&leaf2, &ca);
    assert!(
        matches!(base_result, Err(Error::Revoked { .. })),
        "serial=2 must be Revoked in base alone; got: {base_result:?}"
    );

    // With remove delta: serial=2 un-revoked → Ok(()).
    let with_remove = CrlChecker::with_delta(
        fixture("delta-crl-base.der"),
        fixture("delta-crl-remove.der"),
        NOW,
        DefaultVerifier,
    )
    .expect("construction must succeed");
    let result = with_remove.check_revocation(&leaf2, &ca);
    assert!(
        result.is_ok(),
        "serial=2 removed via removeFromCRL in delta must return Ok(()); got: {result:?}"
    );
}

/// Mixed delta: serial=4 added (revoked), serial=2 removeFromCRL (un-revoked).
/// Verify both effects apply simultaneously.
///
/// Oracle: RFC 5280 §5.2.4: both additions and removals in a delta take effect.
#[test]
fn delta_crl_mixed_add_and_remove() {
    let ca = load_cert("delta-crl-ca.der");
    let leaf2 = load_cert("delta-crl-leaf-2.der");
    let leaf4 = load_cert("delta-crl-leaf-4.der");

    let checker = CrlChecker::with_delta(
        fixture("delta-crl-base.der"),
        fixture("delta-crl-mixed.der"),
        NOW,
        DefaultVerifier,
    )
    .expect("construction must succeed");

    // serial=4 is added by the delta → Revoked.
    let r4 = checker.check_revocation(&leaf4, &ca);
    assert!(
        matches!(r4, Err(Error::Revoked { .. })),
        "serial=4 added by delta must be Revoked; got: {r4:?}"
    );

    // serial=2 is removed by the delta → Ok(()).
    let r2 = checker.check_revocation(&leaf2, &ca);
    assert!(
        r2.is_ok(),
        "serial=2 removed by delta must return Ok(()); got: {r2:?}"
    );
}
