//! Integration tests for `pkix_revocation::OcspChecker`.
//!
//! All DER fixtures in tests/fixtures/ocsp-*.der were generated by
//! gen_ocsp_fixtures.py using pyca/cryptography as the external oracle.
//! Tests run fully offline.
//!
//! Fixture structure:
//!   ocsp-ca.der              — RSA-2048 self-signed OCSP CA (serial=100)
//!   ocsp-leaf-good.der       — leaf cert, serial=1 (not revoked)
//!   ocsp-leaf-revoked.der    — leaf cert, serial=2 (revoked in response fixtures)
//!   ocsp-good.der            — OCSP response: serial=1 → good
//!   ocsp-revoked.der         — OCSP response: serial=2 → revoked, reason=keyCompromise(1)
//!   ocsp-revoked-no-reason.der — OCSP response: serial=2 → revoked, no reason
//!   ocsp-unknown.der         — OCSP response: serial=1 → unknown
//!   ocsp-expired.der         — OCSP response: nextUpdate=2021-01-01 (expired)
//!   ocsp-bad-sig.der         — ocsp-good.der with last signature byte corrupted
//!
//! Cross-CA replay fixtures (generated by gen_ocsp_cross_ca_fixture.py):
//!   ocsp-ca-a.der            — CA-A cert (RSA-2048, CN=OCSP CA-A)
//!   ocsp-ca-b.der            — CA-B cert (RSA-2048, CN=OCSP CA-B)
//!   ocsp-ca-a-leaf.der       — leaf issued by CA-A, serial=1
//!   ocsp-ca-b-leaf.der       — leaf issued by CA-B, serial=1
//!   ocsp-ca-a-good.der       — OCSP "good" for CA-A/serial=1 (issuerNameHash/issuerKeyHash = CA-A)
//!
//! ResponderId fixtures (generated by gen_responder_id_fixtures.py, PKIX-jd7):
//!   ocsp-rid-ca.der          — RSA-2048 CA for ResponderId tests (CN=OCSP RID Test CA)
//!   ocsp-rid-leaf-good.der   — leaf issued by ocsp-rid-ca.der, serial=1
//!   ocsp-rid-good-byname.der — valid response, ResponderId=byName(correct CA name)
//!   ocsp-rid-good-bykey.der  — valid response, ResponderId=byKey(SHA1 of CA SPKI bits)
//!   ocsp-rid-bad-byname.der  — response with byName(CN=Wrong CA), signed with correct key
//!   ocsp-rid-bad-bykey.der   — response with byKey(corrupted SHA1), signed with correct key
//!
//! Validation time: 2026-06-01 00:00:00 UTC = 1_780_272_000.
//! All valid OCSP responses have producedAt=2026-01-01, nextUpdate=2027-01-01.

use der::Decode as _;
use pkix_path::{DefaultVerifier, TrustAnchor};
use pkix_revocation::{Error, OcspChecker, RevocationChecker as _};
use x509_cert::{ext::pkix::crl::CrlReason, Certificate};

/// Unix timestamp used as "now" for all tests (2026-06-01 00:00:00 UTC).
const NOW: u64 = 1_780_272_000;

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("read {name}: {e}"))
}

fn load_cert(name: &str) -> Certificate {
    let der = fixture(name);
    Certificate::from_der(&der).unwrap_or_else(|e| panic!("parse {name}: {e}"))
}

fn checker(response_name: &str) -> OcspChecker<DefaultVerifier> {
    OcspChecker::new(fixture(response_name), NOW, DefaultVerifier)
}

// ---------------------------------------------------------------------------
// Happy path
// ---------------------------------------------------------------------------

/// Good cert (serial=1) against ocsp-good.der → Ok(()).
///
/// Oracle: pyca/cryptography; certStatus=good for serial=1.
#[test]
fn ocsp_good_cert_ok() {
    let ca = load_cert("ocsp-ca.der");
    let good = load_cert("ocsp-leaf-good.der");
    let result = checker("ocsp-good.der").check_revocation(&good, &ca);
    result.expect("good cert must return Ok(())");
}

// ---------------------------------------------------------------------------
// Revoked
// ---------------------------------------------------------------------------

/// Revoked cert (serial=2) against ocsp-revoked.der → Err(Revoked { reason=Some(KeyCompromise) }).
///
/// Oracle: pyca/cryptography; certStatus=revoked, CRLReason=keyCompromise (RFC 5280 §5.3.1 value 1).
#[test]
fn ocsp_cert_revoked_with_reason() {
    let ca = load_cert("ocsp-ca.der");
    let revoked = load_cert("ocsp-leaf-revoked.der");
    let result = checker("ocsp-revoked.der").check_revocation(&revoked, &ca);
    assert!(
        matches!(
            result,
            Err(Error::Revoked {
                reason_code: Some(CrlReason::KeyCompromise),
                ..
            })
        ),
        "revoked cert must return Revoked {{ reason_code: Some(KeyCompromise) }}, got: {result:?}"
    );
}

/// Revoked cert (serial=2) against ocsp-revoked-no-reason.der → Err(Revoked { reason=None }).
///
/// Oracle: pyca/cryptography; certStatus=revoked, no CRLReason extension.
#[test]
fn ocsp_cert_revoked_no_reason() {
    let ca = load_cert("ocsp-ca.der");
    let revoked = load_cert("ocsp-leaf-revoked.der");
    let result = checker("ocsp-revoked-no-reason.der").check_revocation(&revoked, &ca);
    assert!(
        matches!(
            result,
            Err(Error::Revoked {
                reason_code: None,
                ..
            })
        ),
        "revoked cert (no reason) must return Revoked {{ reason_code: None }}, got: {result:?}"
    );
}

// ---------------------------------------------------------------------------
// Unknown status
// ---------------------------------------------------------------------------

/// Cert against ocsp-unknown.der → Err(OcspStatusUnknown).
///
/// Oracle: pyca/cryptography; certStatus=unknown.
#[test]
fn ocsp_unknown_status_returns_error() {
    let ca = load_cert("ocsp-ca.der");
    let good = load_cert("ocsp-leaf-good.der");
    let result = checker("ocsp-unknown.der").check_revocation(&good, &ca);
    assert!(
        matches!(result, Err(Error::OcspStatusUnknown)),
        "unknown certStatus must return OcspStatusUnknown, got: {result:?}"
    );
}

// ---------------------------------------------------------------------------
// Validity window
// ---------------------------------------------------------------------------

/// Valid cert against ocsp-expired.der (nextUpdate=2021-01-01 < NOW=2026) → Err(OcspExpired).
///
/// Oracle: ocsp-expired.der has nextUpdate=2021-01-01 08:00:00 UTC.
#[test]
fn ocsp_expired_response_returns_error() {
    let ca = load_cert("ocsp-ca.der");
    let good = load_cert("ocsp-leaf-good.der");
    let result = checker("ocsp-expired.der").check_revocation(&good, &ca);
    assert!(
        matches!(result, Err(Error::OcspExpired)),
        "expired OCSP response must return OcspExpired, got: {result:?}"
    );
}

// ---------------------------------------------------------------------------
// Signature errors
// ---------------------------------------------------------------------------

/// Valid cert against ocsp-bad-sig.der → Err(OcspSignatureInvalid).
///
/// Oracle: ocsp-bad-sig.der is ocsp-good.der with last signature byte XOR'd 0xFF.
#[test]
fn ocsp_bad_signature_returns_error() {
    let ca = load_cert("ocsp-ca.der");
    let good = load_cert("ocsp-leaf-good.der");
    let result = checker("ocsp-bad-sig.der").check_revocation(&good, &ca);
    assert!(
        matches!(result, Err(Error::OcspSignatureInvalid)),
        "corrupted OCSP signature must return OcspSignatureInvalid, got: {result:?}"
    );
}

// ---------------------------------------------------------------------------
// Issuer hash verification (PKIX-8sh.4)
// ---------------------------------------------------------------------------

/// Cross-CA replay: CA-A's "good" response for serial=1 must NOT validate
/// CA-B's serial=1 cert even though the serial matches.
///
/// The response's CertID.issuerNameHash and issuerKeyHash were computed from
/// CA-A. When verified against CA-B as issuer, the signature or CertID hash check
/// fails → some Err variant (OcspSignatureInvalid or OcspCertIdMismatch).
///
/// Oracle: pyca/cryptography (gen_ocsp_cross_ca_fixture.py).
/// Fixtures: ocsp-ca-a.der, ocsp-ca-b.der, ocsp-ca-b-leaf.der, ocsp-ca-a-good.der.
#[test]
fn ocsp_cross_ca_replay_rejected() {
    let ca_b = load_cert("ocsp-ca-b.der");
    let ca_b_leaf = load_cert("ocsp-ca-b-leaf.der");
    // Use CA-A's response (signed by CA-A's key) against CA-B's leaf.
    // The verifier here is CA-A's key (supplied as a dummy verifier that won't
    // be reached because the signature check uses the issuer SPKI — CA-B here).
    // We use DefaultVerifier; the sig check will fail first OR the hash check
    // fires: either way the response must not return Ok(()).
    //
    // To isolate the issuer-hash check specifically we need the signature to
    // pass. Build a checker using CA-A's response but supply CA-B as issuer:
    // the sig was made with CA-A's key, CA-B has a different key → sig fails
    // before we reach the hash check.
    //
    // The test verifies the combined defence: at minimum, no Ok(()) is returned
    // when the wrong issuer is supplied.
    let checker = OcspChecker::new(fixture("ocsp-ca-a-good.der"), NOW, DefaultVerifier);
    let result = checker.check_revocation(&ca_b_leaf, &ca_b);
    assert!(
        result.is_err(),
        "cross-CA replay must not return Ok(()); got: {result:?}"
    );
    assert!(
        !matches!(result, Ok(())),
        "cross-CA replay must be rejected"
    );
}

/// Same-CA happy path: CA-A's response for CA-A's own leaf must pass.
///
/// Oracle: pyca/cryptography (gen_ocsp_cross_ca_fixture.py).
#[test]
fn ocsp_same_ca_issuer_hash_ok() {
    let ca_a = load_cert("ocsp-ca-a.der");
    let ca_a_leaf = load_cert("ocsp-ca-a-leaf.der");
    let checker = OcspChecker::new(fixture("ocsp-ca-a-good.der"), NOW, DefaultVerifier);
    let result = checker.check_revocation(&ca_a_leaf, &ca_a);
    result.expect("CA-A's response for CA-A's own leaf must return Ok(())");
}

// ---------------------------------------------------------------------------
// Parse errors
// ---------------------------------------------------------------------------

/// Truncated OCSP DER → Err(OcspParseError(_)).
#[test]
fn ocsp_parse_error_truncated_der() {
    let ca = load_cert("ocsp-ca.der");
    let good = load_cert("ocsp-leaf-good.der");
    let truncated = vec![0x30, 0x82, 0x01, 0x00, 0xAA, 0xBB];
    let checker = OcspChecker::new(truncated, NOW, DefaultVerifier);
    let result = checker.check_revocation(&good, &ca);
    assert!(
        matches!(result, Err(Error::OcspParseError(_))),
        "truncated OCSP response must return OcspParseError, got: {result:?}"
    );
}

// ---------------------------------------------------------------------------
// ResponderId verification (PKIX-jd7)
// ---------------------------------------------------------------------------

/// Valid response with ResponderId=byName(correct CA name) → Ok(()).
///
/// Oracle: pyca/cryptography (gen_responder_id_fixtures.py).
/// Fixture: ocsp-rid-good-byname.der has ResponderId=byName(CN=OCSP RID Test CA).
#[test]
fn ocsp_responder_id_byname_correct_accepted() {
    let ca = load_cert("ocsp-rid-ca.der");
    let leaf = load_cert("ocsp-rid-leaf-good.der");
    let checker = OcspChecker::new(fixture("ocsp-rid-good-byname.der"), NOW, DefaultVerifier);
    let result = checker.check_revocation(&leaf, &ca);
    result.expect("byName ResponderId matching issuer subject must return Ok(())");
}

/// Valid response with ResponderId=byKey(SHA-1 of CA SPKI) → Ok(()).
///
/// Oracle: pyca/cryptography (gen_responder_id_fixtures.py).
/// Fixture: ocsp-rid-good-bykey.der has ResponderId=byKey(SHA1(CA SPKI bits)).
#[test]
fn ocsp_responder_id_bykey_correct_accepted() {
    let ca = load_cert("ocsp-rid-ca.der");
    let leaf = load_cert("ocsp-rid-leaf-good.der");
    let checker = OcspChecker::new(fixture("ocsp-rid-good-bykey.der"), NOW, DefaultVerifier);
    let result = checker.check_revocation(&leaf, &ca);
    result.expect("byKey ResponderId matching issuer SPKI SHA-1 must return Ok(())");
}

/// Response with ResponderId=byName(CN=Wrong CA), signed with correct key → Err(OcspResponderIdMismatch).
///
/// The signature verifies (correct key) but the ResponderId name does not match
/// the issuer's subject DN (CN=Wrong CA ≠ CN=OCSP RID Test CA).
///
/// Oracle: pyca/cryptography (gen_responder_id_fixtures.py).
/// Fixture: ocsp-rid-bad-byname.der has byName=CN=Wrong CA, signed by ocsp-rid-ca key.
#[test]
fn ocsp_responder_id_byname_wrong_rejected() {
    let ca = load_cert("ocsp-rid-ca.der");
    let leaf = load_cert("ocsp-rid-leaf-good.der");
    let checker = OcspChecker::new(fixture("ocsp-rid-bad-byname.der"), NOW, DefaultVerifier);
    let result = checker.check_revocation(&leaf, &ca);
    assert!(
        matches!(result, Err(Error::OcspResponderIdMismatch)),
        "byName ResponderId mismatch must return OcspResponderIdMismatch, got: {result:?}"
    );
}

/// Response with ResponderId=byKey(corrupted SHA-1) → Err(OcspSignatureInvalid).
///
/// The byKey hash is inside tbs_response_data (the signed portion); corrupting
/// it invalidates the signature, so signature verification fails before the
/// ResponderId check is reached.
///
/// # Coverage note
///
/// This test exercises the `OcspSignatureInvalid` path, not `OcspResponderIdMismatch`.
/// To reach the `OcspResponderIdMismatch` byKey arm, a fixture would need a valid
/// OCSP signature (signed with key A) but byKey=SHA1(key B). This requires custom
/// ASN.1 construction that signs a specific tbs_response_data — pyca does not
/// support signing with a key that differs from the responder cert's public key.
/// The `byName` test (ocsp_responder_id_byname_wrong_rejected) exercises the same
/// `verify_responder_id_impl` function via its `ByName` arm.
///
/// Oracle: pyca/cryptography (gen_responder_id_fixtures.py).
/// Fixture: ocsp-rid-bad-bykey.der has byKey with first SHA-1 byte XOR 0xFF.
#[test]
fn ocsp_responder_id_bykey_wrong_rejected() {
    let ca = load_cert("ocsp-rid-ca.der");
    let leaf = load_cert("ocsp-rid-leaf-good.der");
    let checker = OcspChecker::new(fixture("ocsp-rid-bad-bykey.der"), NOW, DefaultVerifier);
    let result = checker.check_revocation(&leaf, &ca);
    assert!(
        matches!(result, Err(Error::OcspSignatureInvalid)),
        "corrupted byKey in tbs_response_data must invalidate signature → OcspSignatureInvalid, got: {result:?}"
    );
}

// ---------------------------------------------------------------------------
// check_revocation_against_anchor (PKIX-x1i / OCSP path)
// ---------------------------------------------------------------------------

/// check_revocation_against_anchor with a valid OCSP response and byName ResponderId
/// for a cert issued by the anchor → Ok(()).
///
/// Reuses the ocsp-rid-* fixtures: ocsp-rid-ca.der is treated as the trust
/// anchor, ocsp-rid-leaf-good.der as the cert issued by that anchor.
/// ocsp-rid-good-byname.der is a valid response for that leaf from the anchor CA.
///
/// Oracle: pyca/cryptography (gen_responder_id_fixtures.py).
#[test]
fn ocsp_check_revocation_against_anchor_good() {
    let anchor_cert = load_cert("ocsp-rid-ca.der");
    let anchor = TrustAnchor::from(&anchor_cert);
    let leaf = load_cert("ocsp-rid-leaf-good.der");
    let checker = OcspChecker::new(fixture("ocsp-rid-good-byname.der"), NOW, DefaultVerifier);
    let result = checker.check_revocation_against_anchor(&leaf, &anchor);
    result.expect("valid OCSP response for anchor-issued cert must return Ok(())");
}

/// check_revocation_against_anchor with a corrupted byKey response → Err(OcspSignatureInvalid).
///
/// Same logic as `ocsp_responder_id_bykey_wrong_rejected`: the byKey hash is
/// inside the signed data, so its corruption invalidates the signature.
///
/// The anchor's SPKI SHA-1 must not match the corrupted hash in ocsp-rid-bad-bykey.der.
///
/// Oracle: pyca/cryptography (gen_responder_id_fixtures.py).
#[test]
fn ocsp_check_revocation_against_anchor_bad_responder_id() {
    let anchor_cert = load_cert("ocsp-rid-ca.der");
    let anchor = TrustAnchor::from(&anchor_cert);
    let leaf = load_cert("ocsp-rid-leaf-good.der");
    let checker = OcspChecker::new(fixture("ocsp-rid-bad-bykey.der"), NOW, DefaultVerifier);
    let result = checker.check_revocation_against_anchor(&leaf, &anchor);
    assert!(
        matches!(result, Err(Error::OcspSignatureInvalid)),
        "corrupted byKey in tbs_response_data must invalidate signature → OcspSignatureInvalid, got: {result:?}"
    );
}
