//! Integration tests for `pkix_revocation::OcspChecker`.
//!
//! All DER fixtures in tests/fixtures/ocsp-*.der were generated by
//! gen_ocsp_fixtures.py using pyca/cryptography as the external oracle.
//! Tests run fully offline.
//!
//! Fixture structure:
//!   ocsp-ca.der              — RSA-2048 self-signed OCSP CA (serial=100)
//!   ocsp-leaf-good.der       — leaf cert, serial=1 (not revoked)
//!   ocsp-leaf-revoked.der    — leaf cert, serial=2 (revoked in response fixtures)
//!   ocsp-good.der            — OCSP response: serial=1 → good
//!   ocsp-revoked.der         — OCSP response: serial=2 → revoked, reason=keyCompromise(1)
//!   ocsp-revoked-no-reason.der — OCSP response: serial=2 → revoked, no reason
//!   ocsp-unknown.der         — OCSP response: serial=1 → unknown
//!   ocsp-expired.der         — OCSP response: nextUpdate=2021-01-01 (expired)
//!   ocsp-bad-sig.der         — ocsp-good.der with last signature byte corrupted
//!
//! Validation time: 2026-06-01 00:00:00 UTC = 1_780_272_000.
//! All valid OCSP responses have producedAt=2026-01-01, nextUpdate=2027-01-01.

use der::Decode as _;
use pkix_path::DefaultVerifier;
use pkix_revocation::{Error, OcspChecker, RevocationChecker as _};
use x509_cert::Certificate;

/// Unix timestamp used as "now" for all tests (2026-06-01 00:00:00 UTC).
const NOW: u64 = 1_780_272_000;

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("read {name}: {e}"))
}

fn load_cert(name: &str) -> Certificate {
    let der = fixture(name);
    Certificate::from_der(&der).unwrap_or_else(|e| panic!("parse {name}: {e}"))
}

fn checker(response_name: &str) -> OcspChecker<DefaultVerifier> {
    OcspChecker::new(fixture(response_name), NOW, DefaultVerifier)
}

// ---------------------------------------------------------------------------
// Happy path
// ---------------------------------------------------------------------------

/// Good cert (serial=1) against ocsp-good.der → Ok(()).
///
/// Oracle: pyca/cryptography; certStatus=good for serial=1.
#[test]
fn ocsp_good_cert_ok() {
    let ca = load_cert("ocsp-ca.der");
    let good = load_cert("ocsp-leaf-good.der");
    let result = checker("ocsp-good.der").check_revocation(&good, &ca);
    result.expect("good cert must return Ok(())");
}

// ---------------------------------------------------------------------------
// Revoked
// ---------------------------------------------------------------------------

/// Revoked cert (serial=2) against ocsp-revoked.der → Err(Revoked { reason=Some(1) }).
///
/// Oracle: pyca/cryptography; certStatus=revoked, CRLReason=keyCompromise (1).
#[test]
fn ocsp_cert_revoked_with_reason() {
    let ca = load_cert("ocsp-ca.der");
    let revoked = load_cert("ocsp-leaf-revoked.der");
    let result = checker("ocsp-revoked.der").check_revocation(&revoked, &ca);
    assert!(
        matches!(
            result,
            Err(Error::Revoked {
                reason_code: Some(1),
                ..
            })
        ),
        "revoked cert must return Revoked {{ reason_code: Some(1) }}, got: {result:?}"
    );
}

/// Revoked cert (serial=2) against ocsp-revoked-no-reason.der → Err(Revoked { reason=None }).
///
/// Oracle: pyca/cryptography; certStatus=revoked, no CRLReason extension.
#[test]
fn ocsp_cert_revoked_no_reason() {
    let ca = load_cert("ocsp-ca.der");
    let revoked = load_cert("ocsp-leaf-revoked.der");
    let result = checker("ocsp-revoked-no-reason.der").check_revocation(&revoked, &ca);
    assert!(
        matches!(
            result,
            Err(Error::Revoked {
                reason_code: None,
                ..
            })
        ),
        "revoked cert (no reason) must return Revoked {{ reason_code: None }}, got: {result:?}"
    );
}

// ---------------------------------------------------------------------------
// Unknown status
// ---------------------------------------------------------------------------

/// Cert against ocsp-unknown.der → Err(OcspStatusUnknown).
///
/// Oracle: pyca/cryptography; certStatus=unknown.
#[test]
fn ocsp_unknown_status_returns_error() {
    let ca = load_cert("ocsp-ca.der");
    let good = load_cert("ocsp-leaf-good.der");
    let result = checker("ocsp-unknown.der").check_revocation(&good, &ca);
    assert!(
        matches!(result, Err(Error::OcspStatusUnknown)),
        "unknown certStatus must return OcspStatusUnknown, got: {result:?}"
    );
}

// ---------------------------------------------------------------------------
// Validity window
// ---------------------------------------------------------------------------

/// Valid cert against ocsp-expired.der (nextUpdate=2021-01-01 < NOW=2026) → Err(OcspStatusUnknown).
///
/// Oracle: ocsp-expired.der has nextUpdate=2021-01-01 08:00:00 UTC.
#[test]
fn ocsp_expired_response_returns_error() {
    let ca = load_cert("ocsp-ca.der");
    let good = load_cert("ocsp-leaf-good.der");
    let result = checker("ocsp-expired.der").check_revocation(&good, &ca);
    assert!(
        matches!(result, Err(Error::OcspStatusUnknown)),
        "expired OCSP response must return OcspStatusUnknown, got: {result:?}"
    );
}

// ---------------------------------------------------------------------------
// Signature errors
// ---------------------------------------------------------------------------

/// Valid cert against ocsp-bad-sig.der → Err(OcspSignatureInvalid).
///
/// Oracle: ocsp-bad-sig.der is ocsp-good.der with last signature byte XOR'd 0xFF.
#[test]
fn ocsp_bad_signature_returns_error() {
    let ca = load_cert("ocsp-ca.der");
    let good = load_cert("ocsp-leaf-good.der");
    let result = checker("ocsp-bad-sig.der").check_revocation(&good, &ca);
    assert!(
        matches!(result, Err(Error::OcspSignatureInvalid)),
        "corrupted OCSP signature must return OcspSignatureInvalid, got: {result:?}"
    );
}

// ---------------------------------------------------------------------------
// Parse errors
// ---------------------------------------------------------------------------

/// Truncated OCSP DER → Err(OcspParseError(_)).
#[test]
fn ocsp_parse_error_truncated_der() {
    let ca = load_cert("ocsp-ca.der");
    let good = load_cert("ocsp-leaf-good.der");
    let truncated = vec![0x30, 0x82, 0x01, 0x00, 0xAA, 0xBB];
    let checker = OcspChecker::new(truncated, NOW, DefaultVerifier);
    let result = checker.check_revocation(&good, &ca);
    assert!(
        matches!(result, Err(Error::OcspParseError(_))),
        "truncated OCSP response must return OcspParseError, got: {result:?}"
    );
}
