[package]
name        = "pkix-ac"
description = "RFC 5755 X.509 attribute certificate validation"
version.workspace     = true
edition.workspace     = true
rust-version.workspace = true
license.workspace     = true
repository.workspace  = true
authors.workspace     = true
keywords    = ["x509", "certificate", "attribute-certificate", "pki", "authorization"]
categories  = ["cryptography", "no-std"]

[features]
default = []
std     = ["pkix-path/std", "der/std", "x509-cert/std"]

[dependencies]
pkix-path = { workspace = true }
der        = { workspace = true }
x509-cert  = { workspace = true }
spki       = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
