[package]
name        = "pkix-ac"
description = "RFC 5755 X.509 attribute certificate validation"
version               = "0.1.0"
edition.workspace     = true
rust-version.workspace = true
license.workspace     = true
repository.workspace  = true
authors.workspace     = true
keywords    = ["x509", "certificate", "attr-cert", "pki", "authorization"]
categories  = ["cryptography", "no-std"]

[features]
default = []
std     = ["der/std", "x509-cert/std", "pkix-path/std"]

# Enable serde::Serialize / serde::Deserialize on the public Error type.
serde = ["dep:serde", "pkix-path/serde"]

[dependencies]
pkix-path = { workspace = true }
der        = { workspace = true }
serde      = { workspace = true, optional = true }
x509-cert  = { workspace = true }
spki       = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
