//! Integration tests for fail-closed `NameConstraints` handling in trust-anchor
//! loaders (PKIX-tit4.1).
//!
//! Oracle: DER + PEM fixtures generated by `gen_malformed_nc_fixture.py`
//! (pyca/cryptography). The malformed fixture has a critical
//! `NameConstraints` extension whose `extnValue` is the four bytes
//! `0xFF 0xFE 0x00 0x01` — deterministically invalid DER for the
//! `NameConstraints` SEQUENCE. The good fixture has a well-formed
//! `permittedSubtrees = .example.com`.
//!
//! Per the project test-discipline rule, no test uses `pkix-truststore` as
//! its own oracle: pyca/cryptography produces both the cert bodies and the
//! PEM framing, the corruption is a known constant `b"\xff\xfe\x00\x01"`,
//! and the test asserts that `from_der` / `from_pem` / `from_der_iter` all
//! fail closed on the malformed fixture and accept the good fixture.

use pkix_truststore::{from_der, from_der_iter, from_pem, Error};

const MALFORMED_NC_DER_PATH: &str = "tests/fixtures/anchor-malformed-nc.der";
const MALFORMED_NC_PEM_PATH: &str = "tests/fixtures/anchor-malformed-nc.pem";
const GOOD_NC_DER_PATH: &str = "tests/fixtures/anchor-good-nc.der";
const GOOD_NC_PEM_PATH: &str = "tests/fixtures/anchor-good-nc.pem";

fn read_fixture(path: &str) -> Vec<u8> {
    std::fs::read(path).unwrap_or_else(|e| panic!("fixture {path} missing: {e}"))
}

#[test]
fn from_der_rejects_malformed_nc() {
    let der = read_fixture(MALFORMED_NC_DER_PATH);
    match from_der(&der) {
        Err(Error::Der(_)) => {}
        other => panic!("expected Error::Der for malformed NC anchor; got {other:?}"),
    }
}

#[test]
fn from_der_accepts_good_nc() {
    let der = read_fixture(GOOD_NC_DER_PATH);
    let anchor = from_der(&der).expect("well-formed NC anchor must load");
    assert!(
        anchor.name_constraints.is_some(),
        "good NC anchor must surface name_constraints = Some(..)",
    );
}

#[test]
fn from_pem_rejects_malformed_nc() {
    let pem = read_fixture(MALFORMED_NC_PEM_PATH);
    match from_pem(&pem) {
        Err(Error::Der(_)) => {}
        other => panic!("expected Error::Der for malformed NC anchor in PEM; got {other:?}"),
    }
}

#[test]
fn from_pem_accepts_good_nc() {
    let pem = read_fixture(GOOD_NC_PEM_PATH);
    let anchors = from_pem(&pem).expect("well-formed NC anchor must load");
    assert_eq!(anchors.len(), 1);
    assert!(anchors[0].name_constraints.is_some());
}

#[test]
fn from_pem_rejects_malformed_nc_at_first_block() {
    // Malformed NC anchor appears as the first PEM block; from_pem must
    // surface Error::Der and not silently produce a single-element Vec
    // containing the second (good) anchor.
    let mut pem = read_fixture(MALFORMED_NC_PEM_PATH);
    pem.extend_from_slice(&read_fixture(GOOD_NC_PEM_PATH));
    assert!(matches!(from_pem(&pem), Err(Error::Der(_))));
}

#[test]
fn from_pem_rejects_malformed_nc_at_second_block() {
    // Good anchor at block 0, malformed-NC anchor at block 1. from_pem must
    // surface Error::Der rather than returning Ok with the first anchor.
    let mut pem = read_fixture(GOOD_NC_PEM_PATH);
    pem.extend_from_slice(&read_fixture(MALFORMED_NC_PEM_PATH));
    assert!(matches!(from_pem(&pem), Err(Error::Der(_))));
}

#[test]
fn from_der_iter_reports_index_of_malformed_nc() {
    // A good anchor at index 0, a malformed-NC anchor at index 1.
    // from_der_iter must surface MalformedAnchor { index: 1, source }.
    let good = read_fixture(GOOD_NC_DER_PATH);
    let bad = read_fixture(MALFORMED_NC_DER_PATH);
    let inputs: &[&[u8]] = &[good.as_slice(), bad.as_slice()];
    match from_der_iter(inputs.iter().copied()) {
        Err(Error::MalformedAnchor { index, source: _ }) => assert_eq!(index, 1),
        other => panic!("expected MalformedAnchor {{ index: 1, .. }}; got {other:?}"),
    }
}

#[test]
fn from_der_iter_accepts_good_nc_only() {
    let good = read_fixture(GOOD_NC_DER_PATH);
    let inputs: &[&[u8]] = &[good.as_slice()];
    let anchors = from_der_iter(inputs.iter().copied()).expect("good NC must load");
    assert_eq!(anchors.len(), 1);
    assert!(anchors[0].name_constraints.is_some());
}
