//! Integration tests for [`pkix_identity::verify_dns_name`].
//!
//! Oracle: DER fixtures generated by `tests/fixtures/gen.py` using
//! pyca/cryptography. See `tests/fixtures/README.md` for the SAN
//! contents of each fixture.
//!
//! The fixtures are self-signed leaf certificates; `pkix-identity` is
//! a pure-function library over a single `Certificate` and does not
//! validate chains, so no chain context is needed.

use der::Decode as _;
use pkix_identity::{verify_dns_name, IdentityError, ServerName};
use x509_cert::Certificate;

fn load(name: &str) -> Certificate {
    let path = format!("tests/fixtures/{name}");
    let der = std::fs::read(&path).unwrap_or_else(|e| panic!("fixture not found: {path}: {e}"));
    Certificate::from_der(&der).unwrap_or_else(|e| panic!("invalid DER in {path}: {e}"))
}

// ---------------------------------------------------------------------------
// Exact DNS name matching
// ---------------------------------------------------------------------------

#[test]
fn exact_dns_match() {
    let cert = load("san-exact-dns.der");
    let name = ServerName::dns_name("www.example.com").unwrap();
    assert_eq!(verify_dns_name(&cert, &name), Ok(()));
}

#[test]
fn exact_dns_mismatch_returns_no_matching_san() {
    let cert = load("san-exact-dns.der");
    let name = ServerName::dns_name("api.example.com").unwrap();
    assert_eq!(
        verify_dns_name(&cert, &name),
        Err(IdentityError::NoMatchingSan)
    );
}

#[test]
fn exact_dns_match_is_case_insensitive() {
    let cert = load("san-exact-dns.der");
    let name = ServerName::dns_name("WWW.example.COM").unwrap();
    assert_eq!(verify_dns_name(&cert, &name), Ok(()));
}

#[test]
fn mixed_case_san_matches_lowercase_target() {
    // SAN entry is "Host.Example.COM"; target is "host.example.com".
    let cert = load("san-mixed-case.der");
    let name = ServerName::dns_name("host.example.com").unwrap();
    assert_eq!(verify_dns_name(&cert, &name), Ok(()));
}

// ---------------------------------------------------------------------------
// Wildcard SANs (RFC 6125 §6.4.3)
// ---------------------------------------------------------------------------

#[test]
fn wildcard_matches_single_label() {
    let cert = load("san-wildcard-dns.der");
    let name = ServerName::dns_name("foo.example.com").unwrap();
    assert_eq!(verify_dns_name(&cert, &name), Ok(()));
}

#[test]
fn wildcard_does_not_match_apex() {
    let cert = load("san-wildcard-dns.der");
    let name = ServerName::dns_name("example.com").unwrap();
    assert_eq!(
        verify_dns_name(&cert, &name),
        Err(IdentityError::NoMatchingSan)
    );
}

#[test]
fn wildcard_does_not_span_multiple_labels() {
    let cert = load("san-wildcard-dns.der");
    let name = ServerName::dns_name("a.b.example.com").unwrap();
    assert_eq!(
        verify_dns_name(&cert, &name),
        Err(IdentityError::NoMatchingSan)
    );
}

// ---------------------------------------------------------------------------
// Multi-entry SAN
// ---------------------------------------------------------------------------

#[test]
fn multi_san_matches_any_dns_entry() {
    let cert = load("san-multi-dns.der");
    // First DNS entry.
    let n1 = ServerName::dns_name("www.example.com").unwrap();
    assert_eq!(verify_dns_name(&cert, &n1), Ok(()));
    // Second DNS entry.
    let n2 = ServerName::dns_name("api.example.com").unwrap();
    assert_eq!(verify_dns_name(&cert, &n2), Ok(()));
    // Wildcard entry.
    let n3 = ServerName::dns_name("img.cdn.example.com").unwrap();
    assert_eq!(verify_dns_name(&cert, &n3), Ok(()));
    // Not present.
    let n4 = ServerName::dns_name("other.example.com").unwrap();
    assert_eq!(
        verify_dns_name(&cert, &n4),
        Err(IdentityError::NoMatchingSan)
    );
}

// ---------------------------------------------------------------------------
// IP literal SANs
// ---------------------------------------------------------------------------

#[test]
fn ipv4_san_matches() {
    let cert = load("san-ipv4.der");
    let name = ServerName::ip_address("192.0.2.5").unwrap();
    assert_eq!(verify_dns_name(&cert, &name), Ok(()));
}

#[test]
fn ipv4_san_mismatch_rejects() {
    let cert = load("san-ipv4.der");
    let name = ServerName::ip_address("192.0.2.6").unwrap();
    assert_eq!(
        verify_dns_name(&cert, &name),
        Err(IdentityError::NoMatchingSan)
    );
}

#[test]
fn ipv4_target_does_not_match_dns_san() {
    // san-exact-dns.der has only DnsName entries; an IP target must not
    // match a DnsName.
    let cert = load("san-exact-dns.der");
    let name = ServerName::ip_address("192.0.2.5").unwrap();
    assert_eq!(
        verify_dns_name(&cert, &name),
        Err(IdentityError::NoMatchingSan)
    );
}

#[test]
fn ipv6_san_matches() {
    let cert = load("san-ipv6.der");
    let name = ServerName::ip_address("2001:db8::1").unwrap();
    assert_eq!(verify_dns_name(&cert, &name), Ok(()));
}

#[test]
fn ipv6_san_matches_bracketed_input() {
    let cert = load("san-ipv6.der");
    let name = ServerName::ip_address("[2001:db8::1]").unwrap();
    assert_eq!(verify_dns_name(&cert, &name), Ok(()));
}

#[test]
fn mixed_san_dispatch_by_target_type() {
    let cert = load("san-mixed.der");
    let dns_target = ServerName::dns_name("host.example.com").unwrap();
    assert_eq!(verify_dns_name(&cert, &dns_target), Ok(()));
    let ip_target = ServerName::ip_address("203.0.113.10").unwrap();
    assert_eq!(verify_dns_name(&cert, &ip_target), Ok(()));
    // A DNS-shaped target that happens to be the textual form of the
    // certificate's IP SAN entry MUST NOT match the IpAddress SAN — the
    // dispatch is keyed on the target type, not the textual form.
    // (`203.0.113.10` is a valid LDH string under our normalizer, so
    // dns_name accepts it; the match correctly fails.)
    let dns_lookalike = ServerName::dns_name("203.0.113.10").unwrap();
    assert_eq!(
        verify_dns_name(&cert, &dns_lookalike),
        Err(IdentityError::NoMatchingSan)
    );
}

// ---------------------------------------------------------------------------
// IDN
// ---------------------------------------------------------------------------

#[test]
fn idn_u_label_target_matches_a_label_san() {
    let cert = load("san-idn-alabel.der");
    // Target is U-label form; pkix-identity must convert to A-label
    // before comparing against the SAN entry (which is already an
    // A-label per real-world CABF practice).
    let name = ServerName::dns_name("bücher.example").unwrap();
    assert_eq!(verify_dns_name(&cert, &name), Ok(()));
}

#[test]
fn idn_a_label_target_matches_a_label_san() {
    let cert = load("san-idn-alabel.der");
    let name = ServerName::dns_name("xn--bcher-kva.example").unwrap();
    assert_eq!(verify_dns_name(&cert, &name), Ok(()));
}

// ---------------------------------------------------------------------------
// Missing / CN-only
// ---------------------------------------------------------------------------

#[test]
fn missing_san_returns_missing_san() {
    let cert = load("san-missing.der");
    let name = ServerName::dns_name("anything.example.com").unwrap();
    assert_eq!(
        verify_dns_name(&cert, &name),
        Err(IdentityError::MissingSan)
    );
}

#[test]
fn cn_only_rejected_with_missing_san() {
    // The CN attribute is `leaf`; we deliberately don't fall back to it.
    let cert = load("cn-only.der");
    let cn_target = ServerName::dns_name("leaf").unwrap();
    assert_eq!(
        verify_dns_name(&cert, &cn_target),
        Err(IdentityError::MissingSan)
    );
}
