//! Integration tests for [`pkix_identity::verify_mailbox`].
//!
//! Oracle: DER fixtures generated by `tests/fixtures/gen.py` using
//! pyca/cryptography. See `tests/fixtures/README.md` for the SAN
//! contents of each fixture.
//!
//! The fixtures are self-signed leaf certificates; `pkix-identity` is
//! a pure-function library over a single `Certificate` and does not
//! validate chains, so no chain context is needed.

use der::Decode as _;
use pkix_identity::{verify_mailbox, IdentityError, MailboxName};
use x509_cert::Certificate;

fn load(name: &str) -> Certificate {
    let path = format!("tests/fixtures/{name}");
    let der = std::fs::read(&path).unwrap_or_else(|e| panic!("fixture not found: {path}: {e}"));
    Certificate::from_der(&der).unwrap_or_else(|e| panic!("invalid DER in {path}: {e}"))
}

// ---------------------------------------------------------------------------
// rfc822Name (ASCII) matching
// ---------------------------------------------------------------------------

#[test]
fn rfc822_exact_match() {
    let cert = load("san-rfc822.der");
    let mailbox = MailboxName::parse("alice@example.com").unwrap();
    assert_eq!(verify_mailbox(&cert, &mailbox), Ok(()));
}

#[test]
fn rfc822_local_part_case_sensitive() {
    // SAN entry is `alice@example.com`; target is `Alice@...` — must NOT match.
    let cert = load("san-rfc822.der");
    let mailbox = MailboxName::parse("Alice@example.com").unwrap();
    assert_eq!(
        verify_mailbox(&cert, &mailbox),
        Err(IdentityError::NoMatchingSan)
    );
}

#[test]
fn rfc822_domain_case_insensitive_target() {
    // SAN entry is `alice@example.com`; target uses mixed-case domain — accept.
    let cert = load("san-rfc822.der");
    let mailbox = MailboxName::parse("alice@Example.COM").unwrap();
    assert_eq!(verify_mailbox(&cert, &mailbox), Ok(()));
}

#[test]
fn rfc822_domain_case_insensitive_san() {
    // SAN entry is `alice@Example.COM`; target is lowercase — accept.
    let cert = load("san-rfc822-mixedcase.der");
    let mailbox = MailboxName::parse("alice@example.com").unwrap();
    assert_eq!(verify_mailbox(&cert, &mailbox), Ok(()));
}

#[test]
fn rfc822_mismatch_local() {
    let cert = load("san-rfc822.der");
    let mailbox = MailboxName::parse("bob@example.com").unwrap();
    assert_eq!(
        verify_mailbox(&cert, &mailbox),
        Err(IdentityError::NoMatchingSan)
    );
}

#[test]
fn rfc822_mismatch_domain() {
    let cert = load("san-rfc822.der");
    let mailbox = MailboxName::parse("alice@other.example").unwrap();
    assert_eq!(
        verify_mailbox(&cert, &mailbox),
        Err(IdentityError::NoMatchingSan)
    );
}

// ---------------------------------------------------------------------------
// SmtpUTF8Mailbox (RFC 8398) matching
// ---------------------------------------------------------------------------

#[test]
fn smtputf8_internationalized_local_part_matches() {
    let cert = load("san-smtputf8.der");
    let mailbox = MailboxName::parse("用户@example.com").unwrap();
    assert_eq!(verify_mailbox(&cert, &mailbox), Ok(()));
}

#[test]
fn smtputf8_local_part_case_sensitive() {
    // Pure-ASCII case sensitivity already covered; this test exercises
    // that the SmtpUTF8Mailbox path also treats local-part bytes as
    // case-sensitive (UTF-8 form).
    let cert = load("san-smtputf8.der");
    // Substitute one of the characters with a visually-similar but
    // distinct UTF-8 codepoint — should not match.
    let mailbox = MailboxName::parse("用戶@example.com").unwrap(); // 戶 != 户
    assert_eq!(
        verify_mailbox(&cert, &mailbox),
        Err(IdentityError::NoMatchingSan)
    );
}

#[test]
fn smtputf8_u_label_target_matches_u_label_san() {
    // SAN domain is `bücher.example`; target supplies the same in
    // U-label form.
    let cert = load("san-smtputf8-u-label-domain.der");
    let mailbox = MailboxName::parse("user@bücher.example").unwrap();
    assert_eq!(verify_mailbox(&cert, &mailbox), Ok(()));
}

#[test]
fn smtputf8_a_label_target_matches_u_label_san() {
    // SAN domain is `bücher.example` (U-label, per RFC 8398 §3);
    // target supplies the A-label form. Both forms normalize through
    // idna 2008 to the same canonical A-label before comparison.
    let cert = load("san-smtputf8-u-label-domain.der");
    let mailbox = MailboxName::parse("user@xn--bcher-kva.example").unwrap();
    assert_eq!(verify_mailbox(&cert, &mailbox), Ok(()));
}

#[test]
fn ascii_target_does_not_match_smtputf8_san() {
    // The internationalized SAN otherName carries `用户@example.com`.
    // A pure-ASCII target like `user@example.com` must not match it
    // (different local-part, even though the SAN domain is ASCII).
    let cert = load("san-smtputf8.der");
    let mailbox = MailboxName::parse("user@example.com").unwrap();
    assert_eq!(
        verify_mailbox(&cert, &mailbox),
        Err(IdentityError::NoMatchingSan)
    );
}

#[test]
fn internationalized_target_does_not_match_rfc822_san() {
    // The rfc822Name SAN is `alice@example.com` (ASCII only); an
    // internationalized target cannot match it because rfc822Name is
    // IA5String (ASCII-only on the wire).
    let cert = load("san-rfc822.der");
    let mailbox = MailboxName::parse("用户@example.com").unwrap();
    assert_eq!(
        verify_mailbox(&cert, &mailbox),
        Err(IdentityError::NoMatchingSan)
    );
}

// ---------------------------------------------------------------------------
// Mixed SAN (rfc822 + SmtpUTF8Mailbox)
// ---------------------------------------------------------------------------

#[test]
fn mixed_mailbox_san_matches_ascii_path() {
    let cert = load("san-mailbox-mixed.der");
    let mailbox = MailboxName::parse("alice@example.com").unwrap();
    assert_eq!(verify_mailbox(&cert, &mailbox), Ok(()));
}

#[test]
fn mixed_mailbox_san_matches_utf8_path() {
    let cert = load("san-mailbox-mixed.der");
    let mailbox = MailboxName::parse("用户@example.com").unwrap();
    assert_eq!(verify_mailbox(&cert, &mailbox), Ok(()));
}

#[test]
fn mixed_mailbox_san_rejects_unrelated_mailbox() {
    let cert = load("san-mailbox-mixed.der");
    let mailbox = MailboxName::parse("bob@example.com").unwrap();
    assert_eq!(
        verify_mailbox(&cert, &mailbox),
        Err(IdentityError::NoMatchingSan)
    );
}

// ---------------------------------------------------------------------------
// SAN missing / wrong type
// ---------------------------------------------------------------------------

#[test]
fn missing_san_returns_missing_san() {
    let cert = load("san-missing.der");
    let mailbox = MailboxName::parse("alice@example.com").unwrap();
    assert_eq!(
        verify_mailbox(&cert, &mailbox),
        Err(IdentityError::MissingSan)
    );
}

#[test]
fn dns_only_san_returns_no_matching_san_for_mailbox_target() {
    // san-exact-dns has only DnsName entries; a mailbox target must
    // find no rfc822/otherName entries.
    let cert = load("san-exact-dns.der");
    let mailbox = MailboxName::parse("anyone@example.com").unwrap();
    assert_eq!(
        verify_mailbox(&cert, &mailbox),
        Err(IdentityError::NoMatchingSan)
    );
}
